import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AlertProvider } from "@/context/AlertContext";
import { ToastProvider } from "@/context/ToastContext";

const outfit = localFont({
  src: [
    {
      path: "../public/fonts/outfit/Outfit-VariableFont_wght.ttf",
      style: "normal",
    },
  ],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "TaskFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <AlertProvider>
          <ToastProvider>{children}</ToastProvider>
        </AlertProvider>
      </body>
    </html>
  );
}
